FROM rust:1
RUN apt-get update -qq && apt-get install -y -qq curl xz-utils && rm -rf /var/lib/apt/lists/*
RUN cd /opt && curl -sSL https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz | tar -xJ
ENV PATH=/opt/zig-linux-x86_64-0.13.0:$PATH
RUN cargo install cargo-zigbuild
RUN rustup target add armv7-unknown-linux-gnueabihf
